name: Create tag version

permissions:
  contents: write

on:
  schedule:
    - cron: '45 * * * *'
  workflow_dispatch:

jobs:
  getRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Get Latest Tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Get binhex/arch-plex release
        id: binhextag
        run: |
          EXT_RELEASE=$(curl -s "https://api.github.com/repos/binhex/arch-plex/releases/latest" | jq -r '. | .tag_name')
          if [ -z "${EXT_RELEASE}" ] || [ "${EXT_RELEASE}" == "null" ]; then
            echo "INVALID RELEASE"
            exit 1
          fi
          echo "::set-output name=tag::${EXT_RELEASE}"

      - name: Create Release
        if: ${{ steps.latesttag.outputs.tag }} != ${{ steps.binhextag.outputs.tag }}
        uses: ncipollo/release-action@v1.8.10
        with:
          tag_name: ${{ steps.binhextag.outputs.tag }}
          tag: ${{ steps.binhextag.outputs.tag }}
          body: "Automatic version bump to ${{ steps.binhextag.outputs.tag }}"
          draft: false
          prerelease: false
          allowUpdates: true
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}
