name: DockerHubReadme

on:
  push:
    branches: [ master ]
    paths:
      - 'README.md'
      - '.github/workflows/dockerhub-readme.yml'
      

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: controlol/plex-tmpfs

jobs:
  dockerHubReadme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      # Update the docker hub readme and description
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
